### PR TITLE
ASM skusky 2016

### PR DESCRIPTION
**Pull request by smasty**
Skusky z ASM za rok 2016, obsahuju aj otazky z casti Systemove programovanie.

### CODE REVIEW

**Comment by citruslee** [comment]
Vedel by si toto preklopit do markdownu prosim ta?

**Comment by smasty** [comment]
Nie, su to otazky aj s odpovedami rovno z AISu, rovnako ako po minule roky.

**Comment by citruslee** [comment]
This branch has conflicts that must be resolved

**Comment by citruslee** [comment]
@smasty please resolve the conflicts, so I can merge them

**Comment by smasty** [comment]
Srsly? You should've merged it half a year ago. It's not worth my time anymore.

**Pull request closed without merging**
